In [211]:
import pandas as pd
import numpy as np 
import os

# Import The data

In [212]:
!ls

Goals
GoalsCleaned
RefAndStadium
RefStdCleaned
Result Data
ResultCleaned
Untitled.ipynb

In [213]:

dfs = []
files = os.listdir('Result Data')
files

['2015-2016_result.xlsx',
 '2016-2017_result.xlsx',
 '2017-2018_result.xlsx',
 '2018-2019_result.xlsx',
 '2019-2020_result.xlsx',
 '2020-2021_result.xlsx',
 '2021-2022_result.xlsx',
 '2022-2023_result.xlsx',
 '2023-2024_result.xlsx',
 '2024-2025_result.xlsx']

# Transforming result data

In [214]:
dfs = []
files = os.listdir("Result Data")
files

['2015-2016_result.xlsx',
 '2016-2017_result.xlsx',
 '2017-2018_result.xlsx',
 '2018-2019_result.xlsx',
 '2019-2020_result.xlsx',
 '2020-2021_result.xlsx',
 '2021-2022_result.xlsx',
 '2022-2023_result.xlsx',
 '2023-2024_result.xlsx',
 '2024-2025_result.xlsx']

In [215]:
## create a list of my dataframes
for file in files : 
    df_results = pd.read_excel(rf"Result Data\{file}")
    df_results.name = file.split(".")[0]
    dfs.append(df_results)

In [216]:
## Sample from the last DF
df_results.head()

,match_id,Gameweek,Date,Time,Result,Home team,Away team
0,20240,1,Wed 10/30/24,3:00 PM,1:3,Harras Hodoud,Smouha
1,20241,1,Wed 10/30/24,6:00 PM,0:2,Talaea El Gaish,El Masry
2,20242,1,Thu 10/31/24,3:00 PM,0:0,El Gouna,Zed FC
3,20243,1,Thu 10/31/24,6:00 PM,0:0,Modern Sport,Enppi SC
4,20244,1,Fri 11/1/24,4:00 PM,0:1,Pharco FC,Ittihad Alex

## ID

In [217]:
## Edit the id to be three digits
def threedigits(num):
    num = str(num)
    year = num[:4]
    seq = int(num[4:])
    return year+f"{seq:03}"
print(threedigits(20154))
for df_results in dfs :
    df_results['match_id'] = df_results['match_id'].map(threedigits)

2015004

## Date

In [218]:
for df_results in dfs:
    ## Split the days
    df_results['Day'] = df_results['Date'].map(lambda x : x.split()[0] )
    ## Convert the Date to its format
    df_results['Date'] = pd.to_datetime(df_results['Date'].map(lambda x : x.split()[-1] ) , format = "%m/%d/%y")

## Results

In [219]:
for df_results in dfs :
    ## Add Columns to home and away goals And Who won
    df_results['HomeGoals']= df_results['Result'].map(lambda x : x.split(':')[0]).astype(int)
    df_results['AwayGoals'] = df_results['Result'].map(lambda x : x.split(':')[-1]).astype(int)
    
    def stat(df) : 
        if df['HomeGoals'] > df['AwayGoals'] :
            return 'HomeWin'
        if df['HomeGoals'] < df['AwayGoals'] :
            return 'AwayWin'
        return 'Tie'
    
    df_results['Status'] = df_results.apply(stat ,axis = 1)

## Add season column

In [220]:
for df_results in dfs :
    df_results['Season'] = df_results.name.split('_')[0]

In [221]:
df_results.head()

,match_id,Gameweek,Date,Time,Result,Home team,Away team,Day,HomeGoals,AwayGoals,Status,Season
0,2024000,1,2024-10-30,3:00 PM,1:3,Harras Hodoud,Smouha,Wed,1,3,AwayWin,2024-2025
1,2024001,1,2024-10-30,6:00 PM,0:2,Talaea El Gaish,El Masry,Wed,0,2,AwayWin,2024-2025
2,2024002,1,2024-10-31,3:00 PM,0:0,El Gouna,Zed FC,Thu,0,0,Tie,2024-2025
3,2024003,1,2024-10-31,6:00 PM,0:0,Modern Sport,Enppi SC,Thu,0,0,Tie,2024-2025
4,2024004,1,2024-11-01,4:00 PM,0:1,Pharco FC,Ittihad Alex,Fri,0,1,AwayWin,2024-2025

In [222]:
for df_results in dfs :
    df_results.to_csv(f"ResultCleaned/{df_results.name}_cleaned.csv" , index = False)

# Transforming goals data

In [223]:
dfs = []
files = os.listdir("Goals")
files

['2015-2016_goals.xlsx',
 '2016-2017_goals.xlsx',
 '2017-2018_goals.xlsx',
 '2018-2019_goals.xlsx',
 '2019-2020_goals.xlsx',
 '2020-2021_goals.xlsx',
 '2021-2022_goals.xlsx',
 '2022-2023_goals.xlsx',
 '2023-2024_goals.xlsx',
 '2024-2025_goals.xlsx']

In [224]:
for file in files :
    df_goals = pd.read_excel(rf"Goals\{file}")
    df_goals.name = file.split(".")[0]
    dfs.append(df_goals)

In [225]:
df_goals.head()

,match_id,GoalScorer,OG,Team,Assist,AssistType,Penalty
0,20240,Mahmoud Saber,NaN,Away,Hossam Hassan,Pass,NaN
1,20240,Mohamed Ashraf Roqa,NaN,Home,Mohamed Rabia,Handball,1.0
2,20240,Abdelkabir El Ouadi,NaN,Away,NaN,Unknown,NaN
3,20240,Hossam Hassan,NaN,Away,NaN,Unknown,NaN
4,20241,Salah Mohsen,NaN,Away,Mohamed Makhlouf,Cross,NaN

## ID

In [226]:
## Edit the id to be three digits
def threedigits(num):
    num = str(num)
    year = num[:4]
    seq = int(num[4:])
    return year+f"{seq:03}"
    
print(threedigits(20154))


for df_goals in dfs :
    df_goals['match_id'] = df_goals['match_id'].map(threedigits)

2015004

In [227]:
for df_goals in dfs :
    df_goals.to_csv(f"GoalsCleaned/{df_goals.name}_cleaned.csv" , index = False)

# Transforming referee and stadium data

In [228]:
dfs = []
files = os.listdir("RefAndStadium")
files

['2015-2016_refstd.xlsx',
 '2016-2017_refstd.xlsx',
 '2017-2018_refstd.xlsx',
 '2018-2019_refstd.xlsx',
 '2019-2020_refstd.xlsx',
 '2020-2021_refstd.xlsx',
 '2021-2022_refstd.xlsx',
 '2022-2023_refstd.xlsx',
 '2023-2024_refstd.xlsx',
 '2024-2025_refstd.xlsx']

In [229]:
for file in files :
    df_refstd = pd.read_excel(rf"RefAndStadium\{file}")
    
    df_refstd = df_refstd.rename(columns={'MatchID': 'match_id'})
    df_refstd.name = file.split(".")[0]
    dfs.append(df_refstd)

In [230]:
df_refstd.head()

   match_id             Referee                 Stadium
0     20240  Mohamed El Kallawy                  El Max
1     20241         Tarek Magdi            Suez Stadium
2     20242         Ahmed Hamdi  Khaled Bichara Stadium
3     20243   Mostafa El Shohdi        El Salam Stadium
4     20244  Abdelaziz El Sayed      Alexandria Stadium

## ID

In [231]:
## Edit the id to be three digits
def threedigits(num):
    num = str(num)
    year = num[:4]
    seq = int(num[4:])
    return year+f"{seq:03}"
    


for df_refstd in dfs :
    df_refstd['match_id'] = df_refstd['match_id'].map(threedigits)

In [232]:
for df_refstd in dfs :
    
    df_refstd.to_csv(f"RefStdCleaned/{df_refstd.name}_cleaned.csv" , index = False)